title: Appunti Sparsi
author: Francesco Bruschi
markdown: maruku
pygments: True
JB:
    analytics: 
        provider: google
        google:
            tracking_id: 'UA-36402304-1'
    comments:
        provider: disqus
        disqus:
            short_name: "appunti-sparsi"

safe: true

